### ISSUE TITLE
Getting Issuse of Location Permission Denied and Sms permission Denied

### ISSUE THREAD

**Issue by neosoft07** [WiFire/Android-SDK#1]
I am using Wifire Sdk for First time,I imported Project from git when I installed the app I am getting issuse of Location permission denied and Sms Permission Denied but I have included location permission and sms permission then also I m facing issuse,

And one more issuse,I installed Wifire app from playStore and when i try to add my Wifi to the Wifire it doesnot Authenticate but the password is correct

Please help to resolve this issuse

**Comment by neosoft07** [comment]
pls any one can reply

**Comment by k1slay** [comment]
Hi neosoft07, 

The exception that you are getting is related to the runtime permission system that was added in Android 6.0. More about that here - https://developer.android.com/training/permissions/requesting.html.
- If you pull the new sample app I have updated it to request for runtime permissions on when the exception is thrown. Otherwise you can grant these permissions by going to **System settings->Apps->WiFire SDK->Permissions** and enabling location and sms permissions.
- Regarding your problem with WiFire app, can you try forgetting the network from your WiFi settings before adding the network to WiFire.

**Comment by neosoft07** [comment]
Hello k1slay

I have pulled the new version of wifire project from git but does not have runtime permission,but any ways I have sorted that problem,

but I have added my own wifi network to your Wifire app,but in sample wifire sdk app I m not able to see my network is there any code or effort to do that or any changes in code,

And do we get notification if there is near by wifire n/w because just  near to me there is CCD but I am not getting notification and not able to see the wifi n/w in list of n/w

**Comment by k1slay** [comment]
Hi neosoft07,

The network that you added should appear now in the sample app. It takes roughly 24 hours for a new network to reflect in the SDK.

Yes the WiFire app shows notification for nearby networks, but it only appears if you are already connected to a WiFi network and you have to stay in the WiFi range for around 2 minutes.

**Comment by neosoft07** [comment]
Hello,

 

Let me be clear Suppose there is CCD near to my office I have be in wifi range for atleast 2 minutes to get notification in app but for that do I need to stay connected to any wifi connection to get the nofication,I mean to say do I need to be  connected on wifi for that,

 

And what is range limit of Wifire to get the Wifi .

**Comment by neosoft07** [comment]
Hello,

 

Please reply ,I am waiting from morning

 

 

From: jitendratiwari [mailto:jitendra.tiwari@neosofttech.com] 
Sent: Friday, March 31, 2017 3:23 PM
To: 'WiFire/Android-SDK' <reply@reply.github.com>; 'WiFire/Android-SDK' <Android-SDK@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [WiFire/Android-SDK] Getting Issuse of Location Permission Denied and Sms permission Denied (#1)

 

Hello,

 

Let me be clear Suppose there is CCD near to my office I have be in wifi range for atleast 2 minutes to get notification in app but for that do I need to stay connected to any wifi connection to get the nofication,I mean to say do I need to be  connected on wifi for that,

 

And what is range limit of Wifire to get the Wifi .

**Comment by k1slay** [comment]
Hi neosoft07, 
To get the notification these conditions should be satisfied-

- You should **not be connected to WiFi**.
- The WiFi signal strength should be more than -80dBm. In the system the signal should be at least 2 out of 5 bars.
- You have to stay in the WiFi range for roughly **two minutes** to get the notification.
